name: Dump

on: 
  workflow_dispatch:
    inputs:
      enable-context:
        type: choice
        options:
          - 'true'
          - 'false'
        default: 'true'
        required: true

defaults:
  run:
    shell: bash

jobs:
  debug:
    runs-on: ubuntu-latest
    env:
      ENABLE_CONTEXT: ${{ inputs.enable-context }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dump/
        id: dump
        with:
          enable-context: ${ENABLE_CONTEXT}
      - run: echo "${DATE}"
        env: 
          DATE: ${{ steps.dump.outputs.dumped-date }}